trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Test Stage
  jobs:
  - job: MavenBuild
    displayName: Maven Build Job
    steps:

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install'
      displayName: Build using Maven

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'
      displayName: Run Regression Tests